# Generated by Django 5.2.4 on 2025-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_name_en",
                    models.CharField(max_length=50, verbose_name="食物名稱_英"),
                ),
                (
                    "food_name_zh",
                    models.CharField(max_length=50, verbose_name="食物名稱_中"),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="熱量 (kcal)"
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="蛋白質 (g)"
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="碳水化合物 (g)"
                    ),
                ),
                (
                    "is_recog",
                    models.BooleanField(default=False, verbose_name="是否可辨識"),
                ),
                ("create_user", models.CharField(max_length=20, verbose_name="建立者")),
                ("create_date", models.DateTimeField(verbose_name="建立時間")),
                ("update_user", models.CharField(max_length=20, verbose_name="更新者")),
                ("update_date", models.DateTimeField(verbose_name="更新時間")),
            ],
            options={
                "db_table": "food_recognition_food_nutrition",
            },
        ),
        migrations.CreateModel(
            name="RecogLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_name",
                    models.CharField(max_length=50, verbose_name="圖檔名稱"),
                ),
                (
                    "image_path",
                    models.CharField(max_length=50, verbose_name="圖檔路徑"),
                ),
                (
                    "recog_image_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="辨識圖檔名稱",
                    ),
                ),
                (
                    "recog_content",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="辨識內容"
                    ),
                ),
                ("recog_model_id", models.IntegerField(verbose_name="模型ID")),
                ("model_type", models.IntegerField(verbose_name="辨識類別")),
                ("create_ip", models.CharField(max_length=20, verbose_name="建立者IP")),
                ("create_date", models.DateTimeField(verbose_name="建立時間")),
            ],
            options={
                "db_table": "food_recognition_recog_log",
            },
        ),
        migrations.CreateModel(
            name="RecogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=50, verbose_name="模型名稱"),
                ),
                ("model_type", models.IntegerField(verbose_name="辨識類別")),
                (
                    "model_path",
                    models.CharField(max_length=50, verbose_name="模型路徑"),
                ),
                (
                    "recog_items",
                    models.TextField(max_length=1000, verbose_name="可辨識項目"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="是否啟用"),
                ),
                (
                    "memo",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="備註"
                    ),
                ),
                ("create_user", models.CharField(max_length=20, verbose_name="建立者")),
                ("create_date", models.DateTimeField(verbose_name="建立時間")),
                ("update_user", models.CharField(max_length=20, verbose_name="更新者")),
                ("update_date", models.DateTimeField(verbose_name="更新時間")),
            ],
            options={
                "db_table": "food_recognition_recog_model",
            },
        ),
    ]
