# Generated by Django 5.2.4 on 2025-07-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_recognition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="foodnutrition",
            table="food_nutrition",
        ),
        migrations.AlterModelTable(
            name="recoglog",
            table="recog_log",
        ),
        migrations.AlterModelTable(
            name="recogmodel",
            table="recog_model",
        ),
    ]
