# Generated by Django 5.2.4 on 2025-07-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "food_recognition",
            "0002_alter_foodnutrition_table_alter_recoglog_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="recoglog",
            table="food_recog_log",
        ),
        migrations.AlterModelTable(
            name="recogmodel",
            table="food_recog_model",
        ),
    ]
