# Generated by Django 5.2.4 on 2025-07-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_recognition", "0003_alter_recoglog_table_alter_recogmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodnutrition",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="foodnutrition",
            name="update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
    ]
