# Generated by Django 5.2.4 on 2025-07-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_recognition", "0004_alter_foodnutrition_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodnutrition",
            name="is_recog",
            field=models.BooleanField(default=True, verbose_name="是否可辨識"),
        ),
    ]
