# Generated by Django 5.2.4 on 2025-07-16 05:08

import food_recognition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_recognition", "0005_alter_foodnutrition_is_recog"),
    ]

    operations = [
        migrations.AddField(
            model_name="recogmodel",
            name="model_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=food_recognition.models.model_upload_path,
                verbose_name="上傳模型檔案",
            ),
        ),
        migrations.AlterField(
            model_name="recogmodel",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="recogmodel",
            name="model_path",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="模型檔案路徑"
            ),
        ),
        migrations.AlterField(
            model_name="recogmodel",
            name="update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterModelTable(
            name="recogmodel",
            table="food_recognition_recog_model",
        ),
    ]
